### ISSUE TITLE
.2.1 - script crash when clicking settings button on new game

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#10]
See bottom for more details.

>  125.439 Script lyfactorio.lua:87: for fieldList -> fieldKey=PlayerName fieldValue=.name
>  125.439 Script lyfactorio.lua:87: existGUIElement()fTargetName=fPlayerName result=[FALSE]
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].name
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].name
>  125.439 Script lyfactorio.lua:87: updatingLabelCaption
>  125.439 Script lyfactorio.lua:87: caption target=game.connected_players[1].gui.left.tVars.vPlayerName.caption
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars.vPlayerName
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars.vPlayerName
>  125.439 Script lyfactorio.lua:87: for fieldList -> fieldKey=PlayerPosX fieldValue=.position.x
>  125.439 Script lyfactorio.lua:87: existGUIElement()fTargetName=fPlayerPosX result=[FALSE]
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].position.x
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].position.x
>  125.439 Script lyfactorio.lua:87: updatingLabelCaption
>  125.439 Script lyfactorio.lua:87: caption target=game.connected_players[1].gui.left.tVars.vPlayerPosX.caption
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars.vPlayerPosX
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars.vPlayerPosX
>  125.439 Script lyfactorio.lua:87: for fieldList -> fieldKey=PlayerPosY fieldValue=.position.y
>  125.439 Script lyfactorio.lua:87: existGUIElement()fTargetName=fPlayerPosY result=[FALSE]
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].position.y
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].position.y
>  125.439 Script lyfactorio.lua:87: updatingLabelCaption
>  125.439 Script lyfactorio.lua:87: caption target=game.connected_players[1].gui.left.tVars.vPlayerPosY.caption
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars.vPlayerPosY
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars.vPlayerPosY
>  125.439 Script lyfactorio.lua:87: updateLabels()
>  125.439 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.439 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.439 Script lyfactorio.lua:87: Ly.getGuiStr() guiPos= index=[NIL] context=[NIL]
>  125.439 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.439 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.439 Script lyfactorio.lua:87: Ly.getGuiStr() result==game.connected_players[1].gui.
>  125.439 Script lyfactorio.lua:87: myPlayerStr=game.connected_players[1]
>  125.439 Script lyfactorio.lua:87: myRootStr=game.connected_players[1].gui.left.tVars
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars
>  125.439 Script lyfactorio.lua:87: for fieldList -> fieldKey=PlayerHealth fieldValue=.character.health
>  125.439 Script lyfactorio.lua:87: existGUIElement()fTargetName=fPlayerHealth result=[FALSE]
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].character.health
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].character.health
>  125.439 Script lyfactorio.lua:87: updatingLabelCaption
>  125.439 Script lyfactorio.lua:87: caption target=game.connected_players[1].gui.left.tVars.vPlayerHealth.caption
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars.vPlayerHealth
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>  125.439 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars.vPlayerHealth
>  125.689 Script lyfactorio.lua:87: Ly.getPlayer() index=1 context=[NIL] suffix=
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() caller=getPlayer
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: [table]
>  125.689 Script lyfactorio.lua:87: event onEmptySelection fired
>  125.689 Script lyfactorio.lua:87: destroyLabels()
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() guiPos= index=[NIL] context=[NIL]
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() result==game.connected_players[1].gui.
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() caller=destroyLabels
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: myRootStr=game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: destroyLabels()
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() guiPos= index=[NIL] context=[NIL]
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() result==game.connected_players[1].gui.
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() caller=destroyLabels
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: myRootStr=game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: destroyLabels()
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() guiPos= index=[NIL] context=[NIL]
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>  125.689 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>  125.689 Script lyfactorio.lua:87: Ly.getGuiStr() result==game.connected_players[1].gui.
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() caller=destroyLabels
>  125.689 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars
>  125.689 Script lyfactorio.lua:87: myRootStr=game.connected_players[1].gui.left.tVars
>  125.689 Error MainLoop.cpp:788: Exception at tick 435: Error while running event on_gui_click (ID 1)
> Error while running event on_gui_click (ID 1)
> __PickerExtended__/control.lua:75: attempt to index field 'element' (a nil value)
> stack traceback:
> 	__LyDevGUI__/events/on_gui_click.lua:73: in function <__LyDevGUI__/events/on_gui_click.lua:1>

```
script.on_event(defines.events.on_gui_click, function(event)
    if event.element.name == "picker_renamerX" then
```

from your event.lua
-- workaround for fake events, event object is read only

Not sure I understand what you are doing here. event objects are read/writeable direct refrences

game.raise_event(events.on_gui_click, { event = {}, })

Doing that with any mod that has an on_gui_click event will cause crashes

**Comment by arlyoneel** [comment]
re-open the issue if you have problems again
