### ISSUE TITLE
Game.connected_playes and index

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#6]
```
for i, currentPlayer in pairs(game.connected_players) do
            -- store current working player index for future functions
            Ly.playerIndex = i
```

Just a heads up that the index (i) in this situation is not the players index.  just the first connected player.
you probably want to use

`Ly.playerIndex = currentPlayer.index`

**Comment by arlyoneel** [comment]
ty, will be in next release, its already in last commit
