### ISSUE TITLE
lydevgui 2.1 - script crash on upgrading mod into existing world.

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#7]
__LyDevGUI__/events/on_tick.lua:29: attempt to index field 'lastSelection' (a nil value)

Looks like you possibly changed/added a variable name and didn't account for it in the on_configuration_changed event.

on_init will only run once (when a mod is first installed), after that on_configuration_changed will be run everytime a mod is added/updated/changed.

current workaround would be to remove the mod, load/save the world, re-enable the mod.

**Comment by arlyoneel** [comment]
ty for the information, as you comment before, im new to factorio modding, all information are welcome
added here:
https://github.com/arlyoneel/factorio-lydevgui/commit/231c198757f4d2384509150fb026f46063728d87
