### ISSUE TITLE
.2.1 Error when adding mod to existing game

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#8]
> 14.704 Script lyfactorio.lua:87: updateLabels()
>   14.704 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>   14.704 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>   14.704 Script lyfactorio.lua:87: Ly.getGuiStr() guiPos= index=[NIL] context=[NIL]
>   14.704 Script lyfactorio.lua:87: Ly.getPlayerStr() index=1 context=[NIL] suffix=
>   14.704 Script lyfactorio.lua:87: Ly.getPlayerStr() result==game.connected_players[1]
>   14.704 Script lyfactorio.lua:87: Ly.getGuiStr() result==game.connected_players[1].gui.
>   14.704 Script lyfactorio.lua:87: myPlayerStr=game.connected_players[1]
>   14.704 Script lyfactorio.lua:87: myRootStr=game.connected_players[1].gui.left.tVars
>   14.704 Script lyfactorio.lua:87: Ly.getDynVar() field=game.connected_players[1].gui.left.tVars
>   14.704 Script lyfactorio.lua:87: Ly.getDynVar() caller=updateLabels
>   14.704 Script lyfactorio.lua:87: Ly.getDynVar() fnStr=return game.connected_players[1].gui.left.tVars
>   14.705 Script lyfactorio.lua:87: for fieldList -> fieldKey=PlayerIndex fieldValue=.index
>   14.705 Error MainLoop.cpp:788: Exception at tick 340440: Error while running event on_tick (ID 0)
> Error while running event Custom event (ID 70)
> __LyDevGUI__/libraries/lyfactorio.lua:113: attempt to index local 'myRoot' (a nil value)
> stack traceback:
> 	__LyDevGUI__/events/on_tick.lua:48: in function <__LyDevGUI__/events/on_tick.lua:2>

**Comment by arlyoneel** [comment]
with new event implementation, this is fixed
