### ISSUE TITLE
.2.1 Excessive log() calls

### ISSUE THREAD

**Issue by Nexela** [arlyoneel/factorio-lydevgui#9]
Hopefully just a debug thing but printing that much stuff to the log can make using the log hard

not to mention and a few hours of playing the logfile size will be huge.

take a look at game.write_file()  for writing to a log file for your mod.

**Comment by arlyoneel** [comment]
that was because a i forgot to change logging variable, ill add logic to release script for that, as a workaround you can change value from .libraries/lyconstants.lua  (line 28)

**Comment by arlyoneel** [comment]
https://github.com/arlyoneel/factorio-lydevgui/commit/e730ec90cdedb5e7b3dd709e010b4910c752da96

added to create-release.sh script, it will never happen again.
